---
dependency:
  enabled: false
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: ubuntu-latest
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  options:
    become: true
    extra-vars: "{'testing': true, domain: 'anarres.local'}"
verifier:
  name: testinfra
  options:
    sudo: true
