---

- name: Install gpg package
  ansible.builtin.apt:
    name: gpg
    state: present

- name: Add key for nginx repository
  ansible.builtin.apt_key:
    url: http://nginx.org/keys/nginx_signing.key
  register: nginx_key_added

- name: Add nginx repository
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx"

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx-light

- name: Create web directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "u=rwx,g=r,o="
  with_items:
    - "{{ web_path_default }}"

- name: Configure nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0640

- name: Configure default vhost
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0640
  notify: Restart nginx

- name: Copy default website
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/default/index.html
    owner: www-data
    group: www-data
    mode: "u=r,g=r,o="

- name: Copy robots.txt file
  ansible.builtin.copy:
    src: robots.txt
    dest: /var/www/default/robots.txt
    owner: www-data
    group: www-data
    mode: "u=r,g=r,o="

- name: Enable default vhost
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    owner: www-data
    group: www-data
    state: link
  notify: Restart nginx

- name: Run handlers
  ansible.builtin.meta: flush_handlers
